<?php

return [
  'original' => [
    'Mediterranean Avenue' => [
      'price' => 60,
      'mortgage' => 30,
      'unmortgage' => 33,
      'deed' => 'street',
      'tag' => 'o-mediterranean-avenue',
    ],
    'Baltic Avenue' => [
      'price' => 60,
      'mortgage' => 30,
      'unmortgage' => 33,
      'deed' => 'street',
      'tag' => 'o-baltic-avenue',
    ],
    'Reading Railroad' => [
      'price' => 200,
      'mortgage' => 100,
      'unmortgage' => 110,
      'deed' => 'railroad',
      'tag' => 'o-reading-railroad',
    ],
    'Oriental Avenue' => [
      'price' => 100,
      'mortgage' => 50,
      'unmortgage' => 55,
      'deed' => 'street',
      'tag' => 'o-oriental-avenue',
    ],
    'Vermont Avenue' => [
      'price' => 100,
      'mortgage' => 50,
      'unmortgage' => 55,
      'deed' => 'street',
      'tag' => 'o-vermont-avenue',
    ],
    'Connecticut Avenue' => [
      'price' => 120,
      'mortgage' => 60,
      'unmortgage' => 66,
      'deed' => 'street',
      'tag' => 'o-connecticut-avenue',
    ],
    'St. Charles Place' => [
      'price' => 140,
      'mortgage' => 70,
      'unmortgage' => 77,
      'deed' => 'street',
      'tag' => 'o-st-charles-place',
    ],
    'Electric Company' => [
      'price' => 150,
      'mortgage' => 75,
      'unmortgage' => 83,
      'deed' => 'utility',
      'tag' => 'o-electric-company',
    ],
    'States Avenue' => [
      'price' => 140,
      'mortgage' => 70,
      'unmortgage' => 77,
      'deed' => 'street',
      'tag' => 'o-states-avenue',
    ],
    'Virginia Avenue' => [
      'price' => 160,
      'mortgage' => 80,
      'unmortgage' => 88,
      'deed' => 'street',
      'tag' => 'o-virgina-avenue',
    ],
    'Pennsylvania Railroad' => [
      'price' => 200,
      'mortgage' => 100,
      'unmortgage' => 110,
      'deed' => 'railroad',
      'tag' => 'o-pennsylvania-railroad',
    ],
    'St. James Place' => [
      'price' => 180,
      'mortgage' => 90,
      'unmortgage' => 99,
      'deed' => 'street',
      'tag' => 'o-st-james-place',
    ],
    'Tennessee Avenue' => [
      'price' => 180,
      'mortgage' => 90,
      'unmortgage' => 99,
      'deed' => 'street',
      'tag' => 'o-tennessee-avenue',
    ],
    'New York Avenue' => [
      'price' => 200,
      'mortgage' => 100,
      'unmortgage' => 110,
      'deed' => 'street',
      'tag' => 'o-new-york-avenue',
    ],
    'Kentucky Avenue' => [
      'price' => 220,
      'mortgage' => 110,
      'unmortgage' => 121,
      'deed' => 'street',
      'tag' => 'o-kentucky-avenue',
    ],
    'Indiana Avenue' => [
      'price' => 220,
      'mortgage' => 110,
      'unmortgage' => 121,
      'deed' => 'street',
      'tag' => 'o-indian-avenue',
    ],
    'Illinois Avenue' => [
      'price' => 240,
      'mortgage' => 120,
      'unmortgage' => 132,
      'deed' => 'street',
      'tag' => 'o-illinois-avenue',
    ],
    'B. & O. Railroad' => [
      'price' => 200,
      'mortgage' => 100,
      'unmortgage' => 110,
      'deed' => 'railroad',
      'tag' => 'o-b-o-railroad',
    ],
    'Atlantic Avenue' => [
      'price' => 260,
      'mortgage' => 130,
      'unmortgage' => 143,
      'deed' => 'street',
      'tag' => 'o-atlantic-avenue',
    ],
    'Ventnor Avenue' => [
      'price' => 260,
      'mortgage' => 130,
      'unmortgage' => 143,
      'deed' => 'street',
      'tag' => 'o-ventnor-avenue',
    ],
    'Water Works' => [
      'price' => 150,
      'mortgage' => 75,
      'unmortgage' => 83,
      'deed' => 'utility',
      'tag' => 'o-water-works',
    ],
    'Marvin Gardens' => [
      'price' => 280,
      'mortgage' => 140,
      'unmortgage' => 154,
      'deed' => 'street',
      'tag' => 'o-marvin-gardens',
    ],
    'Pacific Avenue' => [
      'price' => 300,
      'mortgage' => 150,
      'unmortgage' => 165,
      'deed' => 'street',
      'tag' => 'o-pacific-avenue',
    ],
    'North Carolina Avenue' => [
      'price' => 300,
      'mortgage' => 150,
      'unmortgage' => 165,
      'deed' => 'street',
      'tag' => 'o-north-carolina-avenue',
    ],
    'Pennsylvania Avenue' => [
      'price' => 320,
      'mortgage' => 160,
      'unmortgage' => 176,
      'deed' => 'street',
      'tag' => 'o-pennsylvania-avenue',
    ],
    'Short Line' => [
      'price' => 200,
      'mortgage' => 100,
      'unmortgage' => 110,
      'deed' => 'railroad',
      'tag' => 'o-short-line',
    ],
    'Park Place' => [
      'price' => 350,
      'mortgage' => 175,
      'unmortgage' => 193,
      'deed' => 'street',
      'tag' => 'o-park-place',
    ],
    'Boardwalk' => [
      'price' => 400,
      'mortgage' => 200,
      'unmortgage' => 220,
      'deed' => 'street',
      'tag' => 'o-boardwalk',
    ],
  ],
];
