<?php

return [
  'original' => [
    'o-mediterranean-avenue' => [
      'color'           => '#95543D',
      'rent'            => 2,
      'collective_rent' => 4,
      'hotel_rent'      => 250,
      'house_cost'      => 50,
      'hotel_cost'      => 50,
      'tag'             => 'o-mediterranean-avenue',
    ],
    'o-baltic-avenue' => [
      'color'           => '#95543D',
      'rent'            => 4,
      'collective_rent' => 8,
      'hotel_rent'      => 450,
      'house_cost'      => 50,
      'hotel_cost'      => 50,
      'tag'             => 'o-baltic-avenue',
    ],
    'o-oriental-avenue' => [
      'color'           => '#AFDFFB',
      'rent'            => 6,
      'collective_rent' => 12,
      'hotel_rent'      => 550,
      'house_cost'      => 50,
      'hotel_cost'      => 50,
      'tag'             => 'o-oriental-avenue',
    ],
    'o-vermont-avenue' => [
      'color'           => '#AFDFFB',
      'rent'            => 6,
      'collective_rent' => 12,
      'hotel_rent'      => 550,
      'house_cost'      => 50,
      'hotel_cost'      => 50,
      'tag'             => 'o-vermont-avenue',
    ],
    'o-connecticut-avenue' => [
      'color'           => '#AFDFFB',
      'rent'            => 8,
      'collective_rent' => 16,
      'hotel_rent'      => 600,
      'house_cost'      => 50,
      'hotel_cost'      => 50,
      'tag'             => 'o-connecticut-avenue',
    ],
    'o-st-charles-place' => [
      'color'           => '#D54198',
      'rent'            => 10,
      'collective_rent' => 20,
      'hotel_rent'      => 750,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-st-charles-place',
    ],
    'o-states-avenue' => [
      'color'           => '#D54198',
      'rent'            => 10,
      'collective_rent' => 20,
      'hotel_rent'      => 750,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-states-avenue',
    ],
    'o-virgina-avenue' => [
      'color'           => '#D54198',
      'rent'            => 12,
      'collective_rent' => 24,
      'hotel_rent'      => 900,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-virgina-avenue',
    ],
    'o-st-james-place' => [
      'color'           => '#F69231',
      'rent'            => 14,
      'collective_rent' => 28,
      'hotel_rent'      => 950,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-st-james-place',
    ],
    'o-tennessee-avenue' => [
      'color'           => '#F69231',
      'rent'            => 14,
      'collective_rent' => 28,
      'hotel_rent'      => 950,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-tennessee-avenue',
    ],
    'o-new-york-avenue' => [
      'color'           => '#F69231',
      'rent'            => 16,
      'collective_rent' => 32,
      'hotel_rent'      => 1000,
      'house_cost'      => 100,
      'hotel_cost'      => 100,
      'tag'             => 'o-new-york-avenue',
    ],
    'o-kentucky-avenue' => [
      'color'           => '#EA232E',
      'rent'            => 18,
      'collective_rent' => 36,
      'hotel_rent'      => 1050,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-kentucky-avenue',
    ],
    'o-indian-avenue' => [
      'color'           => '#EA232E',
      'rent'            => 18,
      'collective_rent' => 36,
      'hotel_rent'      => 1050,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-indian-avenue',
    ],
    'o-illinois-avenue' => [
      'color'           => '#EA232E',
      'rent'            => 20,
      'collective_rent' => 40,
      'hotel_rent'      => 1100,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-illinois-avenue',
    ],
    'o-atlantic-avenue' => [
      'color'           => '#FEED35',
      'rent'            => 22,
      'collective_rent' => 44,
      'hotel_rent'      => 1150,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-atlantic-avenue',
    ],
    'o-ventnor-avenue' => [
      'color'           => '#FEED35',
      'rent'            => 22,
      'collective_rent' => 44,
      'hotel_rent'      => 1150,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-ventnor-avenue',
    ],
    'o-marvin-gardens' => [
      'color'           => '#FEED35',
      'rent'            => 24,
      'collective_rent' => 48,
      'hotel_rent'      => 1200,
      'house_cost'      => 150,
      'hotel_cost'      => 150,
      'tag'             => 'o-marvin-gardens',
    ],
    'o-pacific-avenue' => [
      'color'           => '#37AE5F',
      'rent'            => 26,
      'collective_rent' => 52,
      'hotel_rent'      => 1275,
      'house_cost'      => 200,
      'hotel_cost'      => 200,
      'tag'             => 'o-pacific-avenue',
    ],
    'o-north-carolina-avenue' => [
      'color'           => '#37AE5F',
      'rent'            => 26,
      'collective_rent' => 52,
      'hotel_rent'      => 1275,
      'house_cost'      => 200,
      'hotel_cost'      => 200,
      'tag'             => 'o-north-carolina-avenue',
    ],
    'o-pennsylvania-avenue' => [
      'color'           => '#37AE5F',
      'rent'            => 28,
      'collective_rent' => 56,
      'hotel_rent'      => 1400,
      'house_cost'      => 200,
      'hotel_cost'      => 200,
      'tag'             => 'o-pennsylvania-avenue',
    ],
    'o-park-place' => [
      'color'           => '#1074B9',
      'rent'            => 35,
      'collective_rent' => 70,
      'hotel_rent'      => 1500,
      'house_cost'      => 200,
      'hotel_cost'      => 200,
      'tag'             => 'o-park-place',
    ],
    'o-boardwalk' => [
      'color'           => '#1074B9',
      'rent'            => 50,
      'collective_rent' => 100,
      'hotel_rent'      => 2000,
      'house_cost'      => 200,
      'hotel_cost'      => 200,
      'tag'             => 'o-boardwalk',
    ],
  ],
];
